### ISSUE TITLE
Negative tax value on cart page when we have discounted product in the cart.

### ISSUE THREAD

**Issue by AlexKonoplyanko** [bigcommerce/bigcommerce-for-wordpress#384] opened 2022-09-01 22:39 UTC
### Expected behavior
Taxes should not show negative value

### Actual behavior
Taxes showed as negative value

### Steps to reproduce behavior

1. Add product to cart which have a discount for customer groups created in promotions.
2. Go to cart there will be negative value for tax

### Screenshot/Video (if applicable)
![image](https://user-images.githubusercontent.com/494084/188024569-68117def-8ef8-454d-aa00-da1190f595c5.png)

![image](https://user-images.githubusercontent.com/494084/188024539-5285646d-15b3-4f2a-8dd0-504300e32621.png)

### Workaround or possible solution

On Cart_Mapper.php we have method calculate_total_tax, where tax calculation is happening.
```
private function calculate_total_tax( $cart_amount, $discount_amount, $coupons_discount_amount, $items ) {
  $item_sum = array_sum( array_map( function ( $item ) {
	  return isset( $item[ 'total_list_price' ][ 'raw' ] ) ? $item[ 'total_list_price' ][ 'raw' ] : 0;
  }, $items ) );
  
  return $cart_amount + $discount_amount + $coupons_discount_amount - $item_sum;
}
```
In my case I had such values in the cart (product price 360 with 10% discount = 324)
$cart_amount = 324
$discount_amount = 0
$coupon_discount_amoun = 0
$item_sum (total_list_price) = 360
Which lead to negative tax value of -36 

As possible solution to resolve that issue we can to use **total_sale_price**, not **total_list_price** in calculations like this ->

```
private function calculate_total_tax( $cart_amount, $discount_amount, $coupons_discount_amount, $items ) {
  $item_sum = array_sum( array_map( function ( $item ) {
	  return isset( $item[ 'total_sale_price' ][ 'raw' ] ) ? $item[ 'total_sale_price' ][ 'raw' ] : 0;
  }, $items ) );
  
  return $cart_amount + $discount_amount + $coupons_discount_amount - $item_sum;
}
```

**Comment by MlKilderkin** [comment] 2022-12-14 18:03
The issue is addressed in 4.36

**Closed by MlKilderkin** 2022-12-14 18:03 UTC
