### ISSUE TITLE
Product sync fails due to channel listings API timeout

### ISSUE THREAD

**Issue by hydagency** [bigcommerce/bigcommerce-for-wordpress#303] opened 2021-09-16 10:39 UTC
### Expected behavior
The product sync works.

### Actual behavior
The import fails due to BC API timeout with the following error in the log:

`[2021-09-15 09:20:12] BigCommerce.ERROR: [504] Error connecting to the API (https://api.bigcommerce.com/stores/n01g2yx1l4/v3/channels/613978/listings) {"response":"[object] (stdClass: {\"status\":504,\"title\":\"\",\"type\":\"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes\",\"errors\":{}})","headers":{"0":"HTTP/1.1 504 Gateway Timeout","Content-Type":"application/json","Transfer-Encoding":"chunked","Connection":"keep-alive","X-Rate-Limit-Requests-Left":"16101489","X-Rate-Limit-Time-Reset-Ms":"16567","X-Rate-Limit-Requests-Quota":"16101495","X-Rate-Limit-Time-Window-Ms":"30000","X-Request-ID":"790b1d455e17de7e214577bfec3732cf","Strict-Transport-Security":"max-age=31536000; includeSubDomains"}}`

### Steps to reproduce behavior

1. Start import (scheduled via cron or manually)

### Additional info
We have ~1000 products synchronized over 5 different channels.
We are using plugin version 4.17.1.

**Comment by usamaibrahim93** [comment] 2021-09-16 20:34
Hi.

We have been facing the same issue for more than a month now. We were patiently waiting for the plugin update hoping that it would fix the issue. But even with 4.17.1 update, the issue still persists.

Our catalog has an excess of 15,000 products and about 150,000 SKUs.

Error screenshot attached below for reference.
![image](https://user-images.githubusercontent.com/43200423/133682033-a67b90b1-624c-44e8-a747-6e7590712e9b.png)

**Comment by yuenvision** [comment] 2021-09-17 16:06
BC Identified an API server capacity issue on their Listing API. They've made some adjustments to the timeouts and bit rate sizes. Can you try your imports again to see if you're seeing any better results and let us know?

**Comment by usamaibrahim93** [comment] 2021-09-17 19:41
> BC Identified an API server capacity issue on their Listing API. They've made some adjustments to the timeouts and bit rate sizes. Can you try your imports again to see if you're seeing any better results and let us know?

Hi @yuenvision  We checked multiple times till yesterday but still ended up with the same issue. From what I know, the plugin update and adjustments to API server capacity were rolled out on 14th September 2021.

**Comment by yuenvision** [comment] 2021-09-17 20:14
Yes, that's correct, however additional adjustments were pushed this afternoon and their data steams are indicating a large increase in performance and far fewer errors. Please let me know if you are seeing any difference on your end.

**Comment by usamaibrahim93** [comment] 2021-09-18 12:47
> Yes, that's correct, however additional adjustments were pushed this afternoon and their data steams are indicating a large increase in performance and far fewer errors. Please let me know if you are seeing any difference on your end.

Thanks for the heads up @yuenvision . I'ma try it out again and let you know!

**Comment by sairum123** [comment] 2021-09-20 09:14
Hi @yuenvision still facing the same error I have tried by increasing and decreasing the batch size as well but no luck.
![image](https://user-images.githubusercontent.com/9851339/133979743-acdceca7-79a4-409a-b3fe-74f016cc125b.png)

**Comment by amckemie** [comment] 2021-09-20 15:09
An update for the community: BigCommerce has pushed out an update that resulted in a 50-60% improvement to the timeouts causing this issue; a downstream API issue is believed to be causing the remaining timeouts and errors. It is currently being worked on.

**Comment by usamaibrahim93** [comment] 2021-09-20 15:11
> An update for the community: BigCommerce has pushed out an update that resulted in a 50-60% improvement to the timeouts causing this issue; a downstream API issue is believed to be causing the remaining timeouts and errors. It is currently being worked on.

Thanks for this update. When can we expect this to be rolled out?

**Comment by amckemie** [comment] 2021-09-20 15:16
At this time we can't be certain, but we are hoping to have more insight into this within the next few days! Hopefully it is something that we can fix ASAP and within the week, but as it is a bug, it's not possible to know this early on an exact timeline.

**Comment by usamaibrahim93** [comment] 2021-09-27 15:03
> At this time we can't be certain, but we are hoping to have more insight into this within the next few days! Hopefully it is something that we can fix ASAP and within the week, but as it is a bug, it's not possible to know this early on an exact timeline.

Good day @amckemie . Do we have any update in this regard? Actually we have a go-live date coming up in mid of October and with this issue still persisting, we are quite unsure about the future of our go-live.
Thank you!

**Comment by suziehyd** [comment] 2021-09-28 08:18
BigCommerce team has told us that the issue has been resolved, but it is still occurring for us. 

I have now attempted synchornisation on the store https://store-jcy3qk9lx2.mybigcommerce.com/ and it failed around 9:10 am UK time. 

Is there an eta on when this issues are to be resolved? We also have a go live coming up and this is currently a blocker.

**Comment by bc-tomfifelski** [comment] 2021-09-28 14:21
@suziehyd Do you have any additional information around the fail attempt that would help us understand the issue?
Logs? 
Error code? 

Is the following information provided still  accurate?

_Steps to reproduce
Start import (scheduled via cron or manually)
Additional info
We have ~1000 products synchronized over 5 different channels.
We are using plugin version 4.17.1._

**Comment by suziehyd** [comment] 2021-09-28 14:45
@bc-tomfifelski yes, that is correct.

**Comment by suziehyd** [comment] 2021-09-28 16:01
<img width="856" alt="Screenshot 2021-09-28 at 15 51 20" src="https://user-images.githubusercontent.com/91527579/135123509-93925ce8-c7d0-4659-8534-b2a3ba41ae4e.png"
<img width="1067" alt="Screenshot 2021-09-28 at 17 00 53" src="https://user-images.githubusercontent.com/91527579/135123522-9c70ccfb-8fcf-4ea9-bae5-6ee7241f7597.png">
<img width="1499" alt="Screenshot 2021-09-28 at 17 01 37" src="https://user-images.githubusercontent.com/91527579/135123610-fb6d340c-2e3d-4509-9b63-205c360ed61b.png">
>

**Comment by sairum123** [comment] 2021-09-29 08:29
HI, @bc-tomfifelski any update regarding my issue? I tried to sync daily to check if it's fixed but still facing the same issue.

**Comment by suziehyd** [comment] 2021-09-29 09:05
Hi @bc-tomfifelski please find below. Currently the import seems to get stuck on the step 19 all the time on our staging environment. 
![image (4)](https://user-images.githubusercontent.com/91527579/135238169-744bb479-dc3a-47fd-988e-a92687d98f11.png)
![image (3)](https://user-images.githubusercontent.com/91527579/135238180-d97536b5-0b16-4e1d-b94d-d6a3efac5362.png)
[log.txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7250481/log.txt)

**Comment by suziehyd** [comment] 2021-09-29 09:25
@bc-tomfifelski https://store-n01g2yx1l4.mybigcommerce.com/manage/dashboard
![image (5)](https://user-images.githubusercontent.com/91527579/135240561-e92be964-42d7-4e30-a0c2-145aaf5608c0.png)
[qa.txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7250575/qa.txt)

**Comment by suziehyd** [comment] 2021-09-29 09:48
@bc-tomfifelsk https://store-rqwfkckwv6.mybigcommerce.com/manage/dashboard
[prod.txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7250770/prod.txt)
i

**Comment by suziehyd** [comment] 2021-09-29 10:00
@bc-tomfifelski please find examples of logs above. We really appreciate your help with getting this resolved, please let me know how we can best assist you further, perhaps a call between our technical teams would be useful?

Thanks,
Suzie

**Comment by suziehyd** [comment] 2021-09-29 11:20
@bc-tomfifelski supplying another set of QA log which contains an error. Hopefully this will help us to get to the bottom of this. 
https://store-n01g2yx1l4.mybigcommerce.com/manage/dashboard
[qa-fail.txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7251371/qa-fail.txt)

**Comment by suziehyd** [comment] 2021-10-01 08:32
[qa-fail (1).txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7265483/qa-fail.1.txt)
<img width="1497" alt="Screenshot 2021-10-01 at 09 29 50" src="https://user-images.githubusercontent.com/91527579/135590080-8c50aa68-918c-451f-bf6f-2bc48075780a.png">
@bc-tomfifelski 
https://store-n01g2yx1l4.mybigcommerce.com/manage/dashboard

**Comment by suziehyd** [comment] 2021-10-04 16:12
https://store-n01g2yx1l4.mybigcommerce.com/manage/dashboard
[Untitled.txt](https://github.com/bigcommerce/bigcommerce-for-wordpress/files/7279614/Untitled.txt)

**Comment by nomanrizwan89** [comment] 2021-10-20 06:30
Is there any update on this issue?

**Comment by yuenvision** [comment] 2022-03-11 16:58
This issue was addressed in [v4.17.1](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/CHANGELOG.md#4171) and also in [v4.19.1](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/CHANGELOG.md#4191). The issue was partly due to some timeouts occurring in the Catalog API response which have since been addressed by BC.

**Closed by yuenvision** 2022-03-11 16:58 UTC
