### ISSUE TITLE
Product Gallery

### ISSUE THREAD

**Issue by 5874** [bigcommerce/bigcommerce-for-wordpress#21] opened 2018-07-11 11:06 UTC
Is there a timeframe for when the product gallery may be fixed? Currently the thumbnails are unresponsive when clicking.

Happy to look at fixing this ourselves through our plugin if possible but don't want to spend time on something that will be fixed in the next release.

Thank you! :)

**Comment by karen-white** [comment] 2018-11-16 16:35
@5874 Following up on a few older issues. We've verified that this works on our end...are you still seeing the problem?

**Comment by amckemie** [comment] 2020-05-07 20:25
We've been unable to reproduce this, so will be closing the issue. Happy to reopen if this comes up again!

**Closed by amckemie** 2020-05-07 20:25 UTC
